export const CLAIM_BOUNDARIES = {
  accuracyScope: "Metrics describe only the committed reviewed corpus and are not global or real-world ScopeForge accuracy.",
  unmeasuredScope: "Rules and ecosystems absent from the corpus are unmeasured by this publication.",
  exceptionalOutcomes: "Error and unsupported outcomes remain explicit and are excluded from derived-metric denominators.",
  benchmarkScope: "Phase 8B synthetic workloads are regression workloads, not a representative production-repository sample.",
  latency: "Catastrophic benchmark ceilings are regression guards, not product latency SLOs.",
  timing: "Wall-clock measurements are environment-sensitive.",
  memory: "RSS delta is observational and is not peak RSS or a memory limit.",
  authority: "Validation publication does not authorize hosted repository acquisition, hosted scanning, passive runtime workers, active CORS workers, or any other production capability.",
} as const;

export function evidenceFixture() {
  return {
    schemaVersion: 1,
    publicationId: "scopeforge-phase-8-release-v1",
    source: {
      repository: "LeDoNguyenTu/ScopeForge",
      phase8aCommit: "8d766f5969427a2e4525f5232b5e28b0f93675bd",
      phase8bCommit: "226a20739871c15d0262d1779b3b013520f47fc6",
      phase8bTree: "50f17f44e770f1179ed2b40b7713e14e864958c0",
      scopeforgeVersion: "0.1.0",
    },
    accuracy: {
      resultSchemaVersion: 1,
      corpus: {
        id: "scopeforge-offline-v1",
        version: "1.0.0",
        contentHash: "3586e2b55cb2e20be5f19997eab7758eef0dcfb7391731b86bc1bdf9bcdd399f",
      },
      coverage: {
        totalCases: 2,
        representedScannerFamilies: ["jsts"],
        representedRuleIds: ["jsts/dynamic-code-execution"],
      },
      aggregate: {
        counts: { tp: 1, fn: 0, fp: 0, tn: 1, error: 0, unsupported: 0, contractMismatch: 0 },
        metrics: { precision: 1, recall: 1, falsePositiveRate: 0, f1: 1 },
      },
      rules: [{
        scanner: "jsts",
        ruleId: "jsts/dynamic-code-execution",
        ruleVersion: "1.0.0",
        caseIds: ["clean-case", "vulnerable-case"],
        counts: { tp: 1, fn: 0, fp: 0, tn: 1, error: 0, unsupported: 0, contractMismatch: 0 },
        metrics: { precision: 1, recall: 1, falsePositiveRate: 0, f1: 1 },
      }],
      cases: [
        {
          caseId: "clean-case",
          scanner: "jsts",
          ruleId: "jsts/dynamic-code-execution",
          label: "clean",
          kind: "tn",
          contractMismatches: [],
          unexpectedRuleIds: [],
          diagnosticCodes: [],
        },
        {
          caseId: "vulnerable-case",
          scanner: "jsts",
          ruleId: "jsts/dynamic-code-execution",
          label: "vulnerable",
          kind: "tp",
          contractMismatches: [],
          unexpectedRuleIds: [],
          diagnosticCodes: [],
        },
      ],
      interpretation: "Metrics describe only the committed covered corpus and are not global ScopeForge accuracy.",
    },
    performance: {
      benchmarkSchemaVersion: 1,
      runsPerProfile: 3,
      environment: {
        nodeVersion: "v22.23.2",
        os: "Ubuntu 24.04.4",
        platform: "linux",
        arch: "x64",
      },
      historical: {
        fixture: "scanner-medium-v1",
        filesAnalyzed: 700,
        findings: 0,
        errors: 0,
        scanDurationMs: 597,
        wallMs: 644,
        rssDeltaBytes: 27738112,
        maxWallMs: 20000,
      },
      profiles: [
        {
          id: "dependency-lockfile-heavy-v1",
          scanner: "sca",
          expectedFiles: 3,
          expectedFindingRuleCounts: {},
          expectedErrors: 0,
          maxWallMs: 20000,
          preflight: { kind: "dependency-lockfile", resolvedComponents: 5000, parserDiagnostics: 0, osvEnabled: false },
          runs: [
            { run: 1, filesAnalyzed: 3, findings: 0, errors: 0, findingRuleCounts: {}, scanDurationMs: 2426, wallMs: 2428, rssDeltaBytes: 1241088 },
            { run: 2, filesAnalyzed: 3, findings: 0, errors: 0, findingRuleCounts: {}, scanDurationMs: 2391, wallMs: 2392, rssDeltaBytes: 4124672 },
            { run: 3, filesAnalyzed: 3, findings: 0, errors: 0, findingRuleCounts: {}, scanDurationMs: 2350, wallMs: 2351, rssDeltaBytes: 3100672 },
          ],
          summary: { minWallMs: 2351, medianWallMs: 2392, maxWallMs: 2428, medianScanDurationMs: 2391, maxRssDeltaBytes: 4124672 },
        },
        {
          id: "iac-heavy-v1",
          scanner: "iac",
          expectedFiles: 601,
          expectedFindingRuleCounts: {
            "iac/docker-floating-base-image": 1,
            "iac/github-actions-write-all-permissions": 1,
            "iac/kubernetes-privileged-container": 1,
            "iac/terraform-aws-public-rds": 1,
          },
          expectedErrors: 0,
          maxWallMs: 30000,
          preflight: { kind: "none" },
          runs: [
            { run: 1, filesAnalyzed: 601, findings: 4, errors: 0, findingRuleCounts: { "iac/docker-floating-base-image": 1, "iac/github-actions-write-all-permissions": 1, "iac/kubernetes-privileged-container": 1, "iac/terraform-aws-public-rds": 1 }, scanDurationMs: 549, wallMs: 588, rssDeltaBytes: 48025600 },
            { run: 2, filesAnalyzed: 601, findings: 4, errors: 0, findingRuleCounts: { "iac/docker-floating-base-image": 1, "iac/github-actions-write-all-permissions": 1, "iac/kubernetes-privileged-container": 1, "iac/terraform-aws-public-rds": 1 }, scanDurationMs: 387, wallMs: 426, rssDeltaBytes: 524288 },
            { run: 3, filesAnalyzed: 601, findings: 4, errors: 0, findingRuleCounts: { "iac/docker-floating-base-image": 1, "iac/github-actions-write-all-permissions": 1, "iac/kubernetes-privileged-container": 1, "iac/terraform-aws-public-rds": 1 }, scanDurationMs: 368, wallMs: 400, rssDeltaBytes: 409600 },
          ],
          summary: { minWallMs: 400, medianWallMs: 426, maxWallMs: 588, medianScanDurationMs: 387, maxRssDeltaBytes: 48025600 },
        },
        {
          id: "source-ast-heavy-v1",
          scanner: "jsts",
          expectedFiles: 1201,
          expectedFindingRuleCounts: { "jsts/dynamic-code-execution": 4 },
          expectedErrors: 0,
          maxWallMs: 30000,
          preflight: { kind: "none" },
          runs: [
            { run: 1, filesAnalyzed: 1201, findings: 4, errors: 0, findingRuleCounts: { "jsts/dynamic-code-execution": 4 }, scanDurationMs: 1234, wallMs: 1287, rssDeltaBytes: 786432 },
            { run: 2, filesAnalyzed: 1201, findings: 4, errors: 0, findingRuleCounts: { "jsts/dynamic-code-execution": 4 }, scanDurationMs: 978, wallMs: 1020, rssDeltaBytes: 131072 },
            { run: 3, filesAnalyzed: 1201, findings: 4, errors: 0, findingRuleCounts: { "jsts/dynamic-code-execution": 4 }, scanDurationMs: 979, wallMs: 1034, rssDeltaBytes: 131072 },
          ],
          summary: { minWallMs: 1020, medianWallMs: 1034, maxWallMs: 1287, medianScanDurationMs: 979, maxRssDeltaBytes: 786432 },
        },
      ],
    },
    limitations: [
      "The reviewed corpus does not represent the full real-world input distribution.",
      "Only eight deterministic rules are represented by the released corpus.",
    ],
    unsupportedScenarios: [
      "Global scanner or repository accuracy claims.",
      "SCA/OSV network-backed advisory accuracy.",
    ],
    claimBoundaries: { ...CLAIM_BOUNDARIES },
    reproduction: {
      install: "npm ci",
      build: "npm run build:cli",
      render: "npm run validation:publication -- --evidence validation/publication/phase-8-release-v1.evidence.json --json output.json --markdown output.md",
      accuracy: "npm run validation:accuracy -- --corpus validation/corpus/offline-v1 --commit <40-hex-commit> --json output.json --markdown output.md",
      benchmark: "npm run benchmark:matrix",
    },
  };
}
