apiVersion: apps/v1
kind: Deployment
metadata:
  name: scopeforge-positive
spec:
  selector:
    matchLabels:
      app: scopeforge
  template:
    metadata:
      labels:
        app: scopeforge
    spec:
      containers:
        - name: app
          image: nginx:1.27.0
          securityContext:
            privileged: true
