FROM docker.io/library/node@sha256:2c87ef9bd3c6a3bd4b472b4bec2ce9d16354b0c574f736c476489d09f560a203

WORKDIR /app
COPY --chown=65532:65532 runtime-worker-entry.js /app/runtime-worker-entry.js

USER 65532:65532
ENTRYPOINT ["/usr/local/bin/node", "/app/runtime-worker-entry.js"]
