import { describe, expect, it } from "vitest";

import type { Finding, ScanResult } from "@/packages/scanner-core/findings/types";
import { serializeHostedScanResult } from "@/packages/scanner-output/hosted/serialize";
import {
  Phase3ImportValidationError,
  validateHostedPhase3Envelope,
} from "@/lib/phase3-import/validation";

function finding(): Finding {
  return {
    id: "legacy-id",
    fingerprint: "sf1:" + "a".repeat(64),
    scanner: "jsts",
    ruleId: "jsts/command-injection",
    ruleVersion: "1.0.0",
    title: "Command injection",
    description: "Untrusted input reaches command execution.",
    severity: "high",
    confidence: "high",
    category: "injection",
    validation: "static_confirmed",
    provenance: "observed",
    location: { file: "src/app.ts", startLine: 7, startColumn: 3, endLine: 7, endColumn: 20 },
    evidence: { summary: "Request input reaches a command execution sink." },
    cwe: ["CWE-78"],
    owasp: ["A03:2021"],
    references: [],
    remediation: {
      summary: "Avoid shell command construction.",
      guidance: "Use an argument API rather than a shell string.",
      verification: "Rescan and confirm the flow is removed.",
    },
    metadata: {},
    baselineState: "new",
  };
}

function scanResult(): ScanResult {
  return {
    scan: {
      root: "/Users/example/private/repo",
      startedAt: "2026-08-26T00:00:00.000Z",
      durationMs: 42,
      scanners: ["jsts@1.0.0"],
    },
    inventory: {
      filesAnalyzed: 10,
      filesSkipped: 1,
      totalBytes: 4096,
      languages: {},
      manifests: [],
      infrastructure: [],
      skippedByReason: {
        default_exclude: 1,
        gitignore: 0,
        scopeforgeignore: 0,
        symlink: 0,
        file_too_large: 0,
        file_limit: 0,
        total_bytes_limit: 0,
        unreadable: 0,
      },
    },
    findings: [finding()],
    errors: [],
    policy: { mode: "report-only", passed: true },
  };
}

function validEnvelope(): Record<string, any> {
  return JSON.parse(serializeHostedScanResult(scanResult(), {
    toolVersion: "0.1.0",
    repositoryUrl: "https://github.com/example/repo",
  }));
}

function expectInvalid(value: unknown, code = "PHASE3_IMPORT_INVALID"): void {
  expect(() => validateHostedPhase3Envelope(value)).toThrow(Phase3ImportValidationError);
  try {
    validateHostedPhase3Envelope(value);
  } catch (error) {
    expect((error as Phase3ImportValidationError).code).toBe(code);
  }
}

describe("hosted Phase 3 envelope validation", () => {
  it("accepts a bounded privacy-reduced envelope generated by ScopeForge", () => {
    const validated = validateHostedPhase3Envelope(validEnvelope());
    expect(validated.schemaVersion).toBe(1);
    expect(validated.repository.canonicalUrl).toBe("https://github.com/example/repo");
    expect(validated.findings[0]?.ruleId).toBe("jsts/command-injection");
  });

  it("rejects forged fields and unknown source descriptors", () => {
    const forged = validEnvelope();
    forged.findings[0].sourceKind = "external-scanner";
    expectInvalid(forged);

    const unknownRule = validEnvelope();
    unknownRule.findings[0].ruleId = "jsts/not-a-rule";
    expectInvalid(unknownRule, "PHASE3_SOURCE_NOT_ALLOWED");

    const unknownVersion = validEnvelope();
    unknownVersion.findings[0].ruleVersion = "999.0.0";
    expectInvalid(unknownVersion, "PHASE3_SOURCE_NOT_ALLOWED");
  });

  it.each([
    "/etc/passwd",
    "../secret.txt",
    "src/../secret.txt",
    "C:/Users/example/secret.txt",
    "src\\secret.ts",
  ])("rejects non-canonical repository-relative paths: %s", (path) => {
    const envelope = validEnvelope();
    envelope.findings[0].location.path = path;
    expectInvalid(envelope);
  });

  it("rejects malformed repository URLs and non-canonical GitHub forms", () => {
    for (const repositoryUrl of [
      "http://github.com/example/repo",
      "https://gitlab.com/example/repo",
      "https://github.com/example/repo/issues",
      "https://github.com/example/repo?token=x",
    ]) {
      const envelope = validEnvelope();
      envelope.repository.canonicalUrl = repositoryUrl;
      expectInvalid(envelope);
    }
  });

  it("rejects unsafe hosted validation values and secret column spans", () => {
    const validation = validEnvelope();
    validation.findings[0].validation = "runtime_validated";
    expectInvalid(validation);

    const secret = validEnvelope();
    secret.findings[0].scanner = "secrets";
    secret.findings[0].ruleId = "secrets/github-token";
    secret.findings[0].ruleVersion = "1.0.0";
    secret.findings[0].location.startColumn = 4;
    expectInvalid(secret);
  });

  it("rejects oversized collections and text instead of truncating", () => {
    const tooMany = validEnvelope();
    tooMany.findings = Array.from({ length: 501 }, () => tooMany.findings[0]);
    expectInvalid(tooMany);

    const longTitle = validEnvelope();
    longTitle.findings[0].title = "x".repeat(241);
    expectInvalid(longTitle);

    const longEvidence = validEnvelope();
    longEvidence.findings[0].evidence.summary = "x".repeat(4097);
    expectInvalid(longEvidence);

    const tooManyScanners = validEnvelope();
    tooManyScanners.scan.scanners = Array.from({ length: 33 }, (_, index) => `jsts@1.0.${index}`);
    expectInvalid(tooManyScanners);
  });

  it("rejects a run reference that does not match the canonical validated payload", () => {
    const envelope = validEnvelope();
    envelope.runRef = "sfh1:" + "0".repeat(64);
    expectInvalid(envelope, "PHASE3_RUN_REF_CONFLICT");
  });
});
